import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // Create default Settings row
  await prisma.settings.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      postcode: "BS7 8NE",
      scrapeIntervalMinutes: 30,
      maxResultsPerSource: 50,
      autotraderEnabled: true,
      motorsEnabled: true,
      gumtreeEnabled: true,
      ebayEnabled: true,
      emailEnabled: false,
      smtpHost: null,
      smtpPort: null,
      smtpUser: null,
      smtpPass: null,
      alertEmail: null,
    },
  });

  console.log("Settings created.");

  // Dates for firstSeen/lastSeen
  const now = new Date();
  const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000);

  const listings = [
    // 1
    {
      id: "clisting0000000001",
      title: "BMW 118i M Sport",
      make: "BMW",
      model: "1 SERIES",
      trim: "M Sport",
      year: 2021,
      price: 16500,
      mileage: 22000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Mineral White",
      engineSize: "1.5L",
      sellerType: "dealer",
      location: "Bristol",
      distance: 3.2,
      listingUrl: "https://www.autotrader.co.uk/car-details/2021-bmw-1-series-118i-m-sport-201234567",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/bmw-1-series/800/600", "https://picsum.photos/seed/bmw-1-interior/800/600"]),
      vin: "WBA1A1C51GV123456",
      fingerprint: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6",
      firstSeen: daysAgo(14),
      lastSeen: daysAgo(1),
      isActive: true,
    },
    // 2
    {
      id: "clisting0000000002",
      title: "Audi A3 35 TFSI S Line",
      make: "Audi",
      model: "A3",
      trim: "S Line",
      year: 2020,
      price: 17200,
      mileage: 31000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Nano Grey",
      engineSize: "1.5L",
      sellerType: "dealer",
      location: "Bath",
      distance: 12.4,
      listingUrl: "https://www.autotrader.co.uk/car-details/2020-audi-a3-35-tfsi-s-line-201234568",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/audi-a3-tfsi/800/600", "https://picsum.photos/seed/audi-a3-side/800/600"]),
      vin: "WAUZZZ8V9LA123456",
      fingerprint: "b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7",
      firstSeen: daysAgo(21),
      lastSeen: daysAgo(2),
      isActive: true,
    },
    // 3
    {
      id: "clisting0000000003",
      title: "CUPRA Formentor 1.5 TSI",
      make: "CUPRA",
      model: "FORMENTOR",
      trim: "V2",
      year: 2022,
      price: 18000,
      mileage: 15000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Petrol Blue",
      engineSize: "1.5L",
      sellerType: "dealer",
      location: "Swindon",
      distance: 38.1,
      listingUrl: "https://www.motors.co.uk/car-details/2022-cupra-formentor-1-5-tsi-301234567",
      source: "motors",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/cupra-formentor/800/600", "https://picsum.photos/seed/cupra-interior/800/600"]),
      vin: null,
      fingerprint: "c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8",
      firstSeen: daysAgo(7),
      lastSeen: daysAgo(0),
      isActive: true,
    },
    // 4
    {
      id: "clisting0000000004",
      title: "SEAT Leon 1.5 TSI FR",
      make: "SEAT",
      model: "LEON",
      trim: "FR",
      year: 2021,
      price: 14500,
      mileage: 28000,
      fuelType: "Petrol",
      transmission: "Manual",
      colour: "Desire Red",
      engineSize: "1.5L",
      sellerType: "private",
      location: "Bristol",
      distance: 5.7,
      listingUrl: "https://www.gumtree.com/cars/bristol/seat-leon-fr/1234567890",
      source: "gumtree",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/seat-leon-fr/800/600", "https://picsum.photos/seed/seat-leon-side/800/600"]),
      vin: null,
      fingerprint: "d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9",
      firstSeen: daysAgo(5),
      lastSeen: daysAgo(0),
      isActive: true,
    },
    // 5
    {
      id: "clisting0000000005",
      title: "Mercedes-Benz A200 AMG Line",
      make: "Mercedes-Benz",
      model: "A CLASS",
      trim: "AMG Line",
      year: 2019,
      price: 15900,
      mileage: 42000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Polar White",
      engineSize: "2.0L",
      sellerType: "dealer",
      location: "Cardiff",
      distance: 47.2,
      listingUrl: "https://www.autotrader.co.uk/car-details/2019-mercedes-benz-a200-amg-line-201234570",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/mercedes-a200/800/600", "https://picsum.photos/seed/mercedes-a-interior/800/600", "https://picsum.photos/seed/mercedes-a-rear/800/600"]),
      vin: "WDD1760121J123456",
      fingerprint: "e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0",
      firstSeen: daysAgo(28),
      lastSeen: daysAgo(3),
      isActive: true,
    },
    // 6
    {
      id: "clisting0000000006",
      title: "Skoda Octavia 2.0 TDI SE",
      make: "Skoda",
      model: "OCTAVIA",
      trim: "SE",
      year: 2020,
      price: 13200,
      mileage: 51000,
      fuelType: "Diesel",
      transmission: "Manual",
      colour: "Brilliant Silver",
      engineSize: "2.0L",
      sellerType: "dealer",
      location: "Gloucester",
      distance: 34.5,
      listingUrl: "https://www.ebay.co.uk/itm/2020-skoda-octavia-2-0-tdi-se/123456789012",
      source: "ebay",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/skoda-octavia-se/800/600", "https://picsum.photos/seed/skoda-octavia-side/800/600"]),
      vin: null,
      fingerprint: "f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1",
      firstSeen: daysAgo(10),
      lastSeen: daysAgo(1),
      isActive: true,
    },
    // 7
    {
      id: "clisting0000000007",
      title: "Toyota C-HR 1.8 Hybrid Icon",
      make: "Toyota",
      model: "C-HR",
      trim: "Icon",
      year: 2022,
      price: 17800,
      mileage: 18000,
      fuelType: "Hybrid",
      transmission: "Automatic",
      colour: "Black",
      engineSize: "1.8L",
      sellerType: "dealer",
      location: "Bristol",
      distance: 7.1,
      listingUrl: "https://www.autotrader.co.uk/car-details/2022-toyota-c-hr-1-8-hybrid-icon-201234572",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/toyota-chr-hybrid/800/600", "https://picsum.photos/seed/toyota-chr-interior/800/600", "https://picsum.photos/seed/toyota-chr-rear/800/600"]),
      vin: "NMTD73BH50R123456",
      fingerprint: "a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3",
      firstSeen: daysAgo(4),
      lastSeen: daysAgo(0),
      isActive: true,
    },
    // 8
    {
      id: "clisting0000000008",
      title: "Honda Civic 1.5 VTEC Sport",
      make: "Honda",
      model: "CIVIC",
      trim: "Sport",
      year: 2021,
      price: 16100,
      mileage: 25000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Lunar Silver",
      engineSize: "1.5L",
      sellerType: "dealer",
      location: "Cheltenham",
      distance: 43.8,
      listingUrl: "https://www.motors.co.uk/car-details/2021-honda-civic-1-5-vtec-sport-301234568",
      source: "motors",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/honda-civic-sport/800/600", "https://picsum.photos/seed/honda-civic-side/800/600"]),
      vin: null,
      fingerprint: "b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4",
      firstSeen: daysAgo(9),
      lastSeen: daysAgo(1),
      isActive: true,
    },
    // 9
    {
      id: "clisting0000000009",
      title: "BMW 320d M Sport",
      make: "BMW",
      model: "3 SERIES",
      trim: "M Sport",
      year: 2019,
      price: 17500,
      mileage: 48000,
      fuelType: "Diesel",
      transmission: "Automatic",
      colour: "Black Sapphire",
      engineSize: "2.0L",
      sellerType: "dealer",
      location: "Bristol",
      distance: 4.9,
      listingUrl: "https://www.autotrader.co.uk/car-details/2019-bmw-3-series-320d-m-sport-201234574",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/bmw-320d-msport/800/600", "https://picsum.photos/seed/bmw-320d-interior/800/600", "https://picsum.photos/seed/bmw-320d-rear/800/600"]),
      vin: "WBA8E9C50KA123456",
      fingerprint: "c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5",
      firstSeen: daysAgo(35),
      lastSeen: daysAgo(2),
      isActive: true,
    },
    // 10
    {
      id: "clisting0000000010",
      title: "Audi A4 35 TDI S Line",
      make: "Audi",
      model: "A4",
      trim: "S Line",
      year: 2020,
      price: 17900,
      mileage: 38000,
      fuelType: "Diesel",
      transmission: "Automatic",
      colour: "Ibis White",
      engineSize: "2.0L",
      sellerType: "dealer",
      location: "Bristol",
      distance: 6.3,
      listingUrl: "https://www.autotrader.co.uk/car-details/2020-audi-a4-35-tdi-s-line-201234575",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/audi-a4-tdi/800/600", "https://picsum.photos/seed/audi-a4-side/800/600"]),
      vin: "WAUZZZF43LN123456",
      fingerprint: "d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6",
      firstSeen: daysAgo(16),
      lastSeen: daysAgo(1),
      isActive: true,
    },
    // 11
    {
      id: "clisting0000000011",
      title: "CUPRA Ateca 1.5 TSI",
      make: "CUPRA",
      model: "ATECA",
      trim: "V2",
      year: 2021,
      price: 17000,
      mileage: 22000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Magnetic Grey",
      engineSize: "1.5L",
      sellerType: "dealer",
      location: "Newport",
      distance: 35.6,
      listingUrl: "https://www.motors.co.uk/car-details/2021-cupra-ateca-1-5-tsi-301234569",
      source: "motors",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/cupra-ateca/800/600", "https://picsum.photos/seed/cupra-ateca-side/800/600"]),
      vin: null,
      fingerprint: "e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7",
      firstSeen: daysAgo(12),
      lastSeen: daysAgo(2),
      isActive: true,
    },
    // 12
    {
      id: "clisting0000000012",
      title: "Mercedes-Benz C200 AMG Line",
      make: "Mercedes-Benz",
      model: "C CLASS",
      trim: "AMG Line",
      year: 2019,
      price: 16800,
      mileage: 44000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Obsidian Black",
      engineSize: "2.0L",
      sellerType: "private",
      location: "Bristol",
      distance: 8.2,
      listingUrl: "https://www.gumtree.com/cars/bristol/mercedes-c200-amg/1234567891",
      source: "gumtree",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/mercedes-c200/800/600", "https://picsum.photos/seed/mercedes-c-interior/800/600", "https://picsum.photos/seed/mercedes-c-side/800/600"]),
      vin: null,
      fingerprint: "f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8",
      firstSeen: daysAgo(20),
      lastSeen: daysAgo(1),
      isActive: true,
    },
    // 13
    {
      id: "clisting0000000013",
      title: "BMW 218i M Sport",
      make: "BMW",
      model: "2 SERIES",
      trim: "M Sport",
      year: 2020,
      price: 15300,
      mileage: 33000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Alpine White",
      engineSize: "1.5L",
      sellerType: "dealer",
      location: "Weston-super-Mare",
      distance: 22.4,
      listingUrl: "https://www.autotrader.co.uk/car-details/2020-bmw-2-series-218i-m-sport-201234577",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/bmw-218i-gran/800/600", "https://picsum.photos/seed/bmw-218i-side/800/600"]),
      vin: "WBA2N31040V123456",
      fingerprint: "a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9",
      firstSeen: daysAgo(8),
      lastSeen: daysAgo(0),
      isActive: true,
    },
    // 14
    {
      id: "clisting0000000014",
      title: "Skoda Octavia vRS 2.0 TSI",
      make: "Skoda",
      model: "OCTAVIA",
      trim: "vRS",
      year: 2021,
      price: 17200,
      mileage: 21000,
      fuelType: "Petrol",
      transmission: "Manual",
      colour: "Race Blue",
      engineSize: "2.0L",
      sellerType: "private",
      location: "Bristol",
      distance: 4.1,
      listingUrl: "https://www.gumtree.com/cars/bristol/skoda-octavia-vrs/1234567892",
      source: "gumtree",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/skoda-octavia-vrs/800/600", "https://picsum.photos/seed/skoda-vrs-interior/800/600"]),
      vin: null,
      fingerprint: "b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0",
      firstSeen: daysAgo(6),
      lastSeen: daysAgo(0),
      isActive: true,
    },
    // 15
    {
      id: "clisting0000000015",
      title: "Toyota RAV4 2.5 VVT-i Hybrid",
      make: "Toyota",
      model: "RAV4",
      trim: "Design",
      year: 2019,
      price: 17700,
      mileage: 55000,
      fuelType: "Hybrid",
      transmission: "Automatic",
      colour: "White Pearl",
      engineSize: "2.5L",
      sellerType: "dealer",
      location: "Swindon",
      distance: 37.9,
      listingUrl: "https://www.autotrader.co.uk/car-details/2019-toyota-rav4-2-5-hybrid-201234579",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/toyota-rav4-hybrid/800/600", "https://picsum.photos/seed/toyota-rav4-side/800/600", "https://picsum.photos/seed/toyota-rav4-rear/800/600"]),
      vin: "JTMBZ3FV5KD123456",
      fingerprint: "c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1",
      firstSeen: daysAgo(25),
      lastSeen: daysAgo(3),
      isActive: true,
    },
    // 16
    {
      id: "clisting0000000016",
      title: "Honda HR-V 1.5 i-VTEC EX",
      make: "Honda",
      model: "HR-V",
      trim: "EX",
      year: 2020,
      price: 15100,
      mileage: 29000,
      fuelType: "Petrol",
      transmission: "Manual",
      colour: "Lunar Silver",
      engineSize: "1.5L",
      sellerType: "dealer",
      location: "Bristol",
      distance: 9.4,
      listingUrl: "https://www.ebay.co.uk/itm/2020-honda-hr-v-1-5-i-vtec-ex/123456789013",
      source: "ebay",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/honda-hrv-ex/800/600", "https://picsum.photos/seed/honda-hrv-side/800/600"]),
      vin: null,
      fingerprint: "d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2",
      firstSeen: daysAgo(11),
      lastSeen: daysAgo(1),
      isActive: true,
    },
    // 17
    {
      id: "clisting0000000017",
      title: "SEAT Ateca 1.5 TSI FR",
      make: "SEAT",
      model: "ATECA",
      trim: "FR",
      year: 2021,
      price: 15600,
      mileage: 26000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Mystery Blue",
      engineSize: "1.5L",
      sellerType: "dealer",
      location: "Bath",
      distance: 13.2,
      listingUrl: "https://www.motors.co.uk/car-details/2021-seat-ateca-1-5-tsi-fr-301234570",
      source: "motors",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/seat-ateca-fr/800/600", "https://picsum.photos/seed/seat-ateca-side/800/600"]),
      vin: null,
      fingerprint: "e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3",
      firstSeen: daysAgo(13),
      lastSeen: daysAgo(2),
      isActive: true,
    },
    // 18
    {
      id: "clisting0000000018",
      title: "Audi Q3 35 TFSI S Line",
      make: "Audi",
      model: "Q3",
      trim: "S Line",
      year: 2020,
      price: 17500,
      mileage: 32000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Floret Silver",
      engineSize: "1.5L",
      sellerType: "dealer",
      location: "Bristol",
      distance: 5.8,
      listingUrl: "https://www.autotrader.co.uk/car-details/2020-audi-q3-35-tfsi-s-line-201234581",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/audi-q3-sline/800/600", "https://picsum.photos/seed/audi-q3-interior/800/600", "https://picsum.photos/seed/audi-q3-rear/800/600"]),
      vin: "WAUZZZ83ZLN123456",
      fingerprint: "f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4",
      firstSeen: daysAgo(18),
      lastSeen: daysAgo(1),
      isActive: true,
    },
    // 19
    {
      id: "clisting0000000019",
      title: "BMW 118d Sport",
      make: "BMW",
      model: "1 SERIES",
      trim: "Sport",
      year: 2021,
      price: 16200,
      mileage: 24000,
      fuelType: "Diesel",
      transmission: "Automatic",
      colour: "Glacier Silver",
      engineSize: "2.0L",
      sellerType: "dealer",
      location: "Chippenham",
      distance: 18.7,
      listingUrl: "https://www.autotrader.co.uk/car-details/2021-bmw-1-series-118d-sport-201234582",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/bmw-118d-sport/800/600", "https://picsum.photos/seed/bmw-118d-side/800/600"]),
      vin: "WBA1A3C53GV123457",
      fingerprint: "a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5",
      firstSeen: daysAgo(7),
      lastSeen: daysAgo(0),
      isActive: true,
    },
    // 20
    {
      id: "clisting0000000020",
      title: "Mercedes-Benz GLA 200",
      make: "Mercedes-Benz",
      model: "GLA CLASS",
      trim: "AMG Line",
      year: 2022,
      price: 17900,
      mileage: 17000,
      fuelType: "Petrol",
      transmission: "Automatic",
      colour: "Mountain Grey",
      engineSize: "2.0L",
      sellerType: "dealer",
      location: "Bristol",
      distance: 6.5,
      listingUrl: "https://www.autotrader.co.uk/car-details/2022-mercedes-benz-gla-200-amg-line-201234583",
      source: "autotrader",
      imageUrls: JSON.stringify(["https://picsum.photos/seed/mercedes-gla200/800/600", "https://picsum.photos/seed/mercedes-gla-interior/800/600", "https://picsum.photos/seed/mercedes-gla-rear/800/600"]),
      vin: "WDC2539031J123456",
      fingerprint: "b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6",
      firstSeen: daysAgo(3),
      lastSeen: daysAgo(0),
      isActive: true,
    },
  ];

  console.log("Creating listings...");
  for (const listing of listings) {
    await prisma.listing.upsert({
      where: { fingerprint: listing.fingerprint },
      update: { imageUrls: listing.imageUrls, price: listing.price, lastSeen: new Date() },
      create: listing,
    });
  }

  console.log("Creating price history entries...");

  // Price drops for listings 1, 5, 9, 12, 18
  const priceDrops = [
    {
      listingId: "clisting0000000001",
      price: 16500 + 1200, // was £17,700
      recordedAt: daysAgo(14),
    },
    {
      listingId: "clisting0000000005",
      price: 15900 + 900, // was £16,800
      recordedAt: daysAgo(21),
    },
    {
      listingId: "clisting0000000009",
      price: 17500 + 1500, // was £19,000
      recordedAt: daysAgo(28),
    },
    {
      listingId: "clisting0000000012",
      price: 16800 + 800, // was £17,600
      recordedAt: daysAgo(14),
    },
    {
      listingId: "clisting0000000018",
      price: 17500 + 1000, // was £18,500
      recordedAt: daysAgo(14),
    },
  ];

  for (const drop of priceDrops) {
    await prisma.priceHistory.create({ data: drop });
  }

  console.log("Creating saved searches...");

  const savedSearch1 = await prisma.savedSearch.upsert({
    where: { id: "csavedsearch000001" },
    update: {},
    create: {
      id: "csavedsearch000001",
      name: "BMW 1 Series Auto Bristol",
      filters: JSON.stringify({
        make: "BMW",
        model: "1 SERIES",
        transmission: "Automatic",
        priceMax: 18000,
        yearMin: 2019,
      }),
      lastViewed: daysAgo(1),
      newCount: 2,
      emailAlert: false,
      desktopAlert: true,
      createdAt: daysAgo(30),
    },
  });

  const savedSearch2 = await prisma.savedSearch.upsert({
    where: { id: "csavedsearch000002" },
    update: {},
    create: {
      id: "csavedsearch000002",
      name: "Hybrid Under £18k",
      filters: JSON.stringify({
        fuelTypes: ["Hybrid"],
        priceMax: 18000,
        yearMin: 2019,
      }),
      lastViewed: daysAgo(2),
      newCount: 1,
      emailAlert: false,
      desktopAlert: true,
      createdAt: daysAgo(30),
    },
  });

  console.log("Creating saved cars...");

  await prisma.savedCar.upsert({
    where: { id: "csavedcar000000001" },
    update: {},
    create: {
      id: "csavedcar000000001",
      listingId: "clisting0000000001",
      notes: "Love the M Sport pack",
      priceAtSave: 16500,
      savedAt: daysAgo(10),
    },
  });

  await prisma.savedCar.upsert({
    where: { id: "csavedcar000000002" },
    update: {},
    create: {
      id: "csavedcar000000002",
      listingId: "clisting0000000002",
      notes: "Check service history",
      priceAtSave: 17200,
      savedAt: daysAgo(8),
    },
  });

  console.log("Seed complete!");
  console.log(`  - 1 Settings row`);
  console.log(`  - 20 Listings`);
  console.log(`  - 5 PriceHistory entries (price drops)`);
  console.log(`  - 2 SavedSearches`);
  console.log(`  - 2 SavedCars`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
